# Generated by Django 3.0.5 on 2020-06-13 05:50

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('hsc_year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020)),
                ('school', models.CharField(max_length=100)),
                ('ssc_year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('mentoring_subject', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=126, size=6)),
                ('level', models.CharField(choices=[('hsc', 'HSC'), ('ssc', 'SSC')], default='hsc', max_length=100)),
                ('deparment', models.CharField(choices=[('science', 'SCIENCE'), ('business studies', 'BUSINESS STUDIES'), ('english', 'ENGLISH'), ('ict', 'ICT')], default='Science', max_length=100)),
                ('summary_of_activites', django_mysql.models.ListTextField(models.CharField(max_length=100), size=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(help_text='Enter your address', max_length=255)),
                ('contact_no', models.CharField(help_text='Enter contact no', max_length=20)),
                ('fb_link', models.CharField(help_text='Enter facebook profile link', max_length=255)),
                ('linkedin_link', models.CharField(help_text='Enter linkedin \tprofile link', max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='teachers_pic')),
                ('gender', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
