# Generated by Django 2.1.8 on 2020-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='deparment',
            field=models.CharField(default='Science', max_length=100),
        ),
    ]
