# Generated by Django 2.1.8 on 2020-04-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_detail_deparment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='deparment',
            field=models.CharField(choices=[('science', 'SCIENCE'), ('business studies', 'BUSINESS STUDIES'), ('ict', 'ICT')], default='Science', max_length=100),
        ),
    ]
