# Generated by Django 2.1.8 on 2020-04-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200418_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='level',
            field=models.CharField(choices=[('hsc', 'HSC'), ('ssc', 'SSC')], default='hsc', max_length=100),
        ),
    ]
