# Generated by Django 2.1.8 on 2020-04-18 15:31

from django.db import migrations, models
import django.utils.timezone
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_detail_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='college',
            field=models.CharField(default=teacher.models.contact_default, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='hsc_passing_year',
            field=models.CharField(default=teacher.models.contact_default, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='school',
            field=models.CharField(default=teacher.models.contact_default, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='ssc_passing_year',
            field=models.CharField(default=teacher.models.contact_default, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_detail',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
