# Generated by Django 2.1.8 on 2020-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20200418_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='college',
            field=models.CharField(max_length=100),
        ),
    ]
