# Generated by Django 2.1.8 on 2020-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200418_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='hsc_passing_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_detail',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_detail',
            name='ssc_passing_year',
            field=models.CharField(max_length=100),
        ),
    ]
