# Generated by Django 2.1.8 on 2020-04-18 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20200418_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
        ),
    ]
