# Generated by Django 2.1.8 on 2020-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20200418_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_detail',
            name='hsc_passing_year',
        ),
        migrations.RemoveField(
            model_name='teacher_detail',
            name='ssc_passing_year',
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='hsc_year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020, max_length=4, verbose_name='year'),
        ),
    ]
