# Generated by Django 2.1.8 on 2020-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20200418_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='contact_no',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='fb_link',
            field=models.CharField(default='hello', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='linkedin_link',
            field=models.CharField(default='hello', max_length=255),
        ),
    ]
