# Generated by Django 2.1.8 on 2020-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20200418_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='linkedin_link',
            field=models.CharField(help_text='Contact phone number', max_length=255),
        ),
    ]
