# Generated by Django 2.1.8 on 2020-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20200418_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='contact_no',
            field=models.CharField(help_text='Enter contact no', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_detail',
            name='fb_link',
            field=models.CharField(help_text='Enter facebook profile link', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher_detail',
            name='linkedin_link',
            field=models.CharField(help_text='Enter linkedin \tprofile link', max_length=255),
        ),
    ]
