# Generated by Django 2.1.8 on 2020-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20200418_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
