# Generated by Django 2.1.8 on 2020-04-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_teacher_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='teachers_pic'),
        ),
    ]
