# Generated by Django 2.1.8 on 2020-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_auto_20200418_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='deparment',
            field=models.CharField(choices=[('science', 'SCIENCE'), ('business studies', 'BUSINESS STUDIES'), ('english', 'ENGLISH'), ('ict', 'ICT')], default='Science', max_length=100),
        ),
    ]
