# Generated by Django 2.1.8 on 2020-04-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_auto_20200418_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_detail',
            new_name='TeachersInfo',
        ),
    ]
