# Generated by Django 2.1.8 on 2020-04-24 15:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_auto_20200420_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersinfo',
            name='widget_group_ids',
            field=django_mysql.models.ListTextField(models.CharField(max_length=10), default='Test', size=100),
        ),
    ]
