# Generated by Django 2.1.8 on 2020-04-24 15:49

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_teachersinfo_widget_group_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersinfo',
            name='widget_group_ids',
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='summary_of_activites',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default='Test', size=100),
        ),
    ]
