# Generated by Django 2.1.8 on 2020-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_teachersinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinfo',
            name='address',
            field=models.CharField(help_text='Enter your address', max_length=255),
        ),
    ]
