# Generated by Django 2.1.8 on 2020-04-24 19:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_auto_20200424_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinfo',
            name='mentoring_subject',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=126, size=6),
        ),
    ]
