# Generated by Django 3.0.5 on 2020-05-01 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('time', models.TimeField()),
                ('enrty_fee', models.IntegerField()),
                ('banner', models.ImageField(default='default.jpg', upload_to='events_banner')),
            ],
        ),
    ]
