# Generated by Django 3.0.5 on 2020-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200501_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(default='events_banner/default.jpg', upload_to='events_banner'),
        ),
    ]
