# Generated by Django 3.0.5 on 2020-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200501_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addess',
            field=models.CharField(default='', max_length=100),
        ),
    ]
