# Generated by Django 3.0.5 on 2020-05-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_addess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='addess',
            new_name='address',
        ),
    ]
