# Generated by Django 3.0.5 on 2020-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200502_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
