# Generated by Django 3.0.5 on 2020-04-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0025_auto_20200424_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_chapter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_details', models.CharField(max_length=1000)),
                ('dept', models.CharField(choices=[('SCIENCE', 'Science'), ('BUSINESS STUDIES', 'Business Studies'), ('ENGLISH', 'English'), ('ICT', 'Ict')], default='Science', max_length=100)),
                ('level', models.CharField(choices=[('HSC', 'HSC'), ('SSC', 'SSC')], default='HSC', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_topic', models.CharField(max_length=200)),
                ('name_of_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Chapter')),
                ('name_of_teacher', models.ManyToManyField(to='teacher.TeachersInfo')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
