# Generated by Django 2.1.8 on 2020-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200419_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('business studies', 'BUSINESS STUDIES'), ('english', 'ENGLISH'), ('ict', 'ICT')], default='SCIENCE', max_length=100),
        ),
    ]
