# Generated by Django 2.1.8 on 2020-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200419_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(choices=[('science', 'SCIENCE'), ('BUSINESS STUDIES', 'Business Studies'), ('ENGLISH', 'English'), ('ICT', 'Ict')], default='SCIENCE', max_length=100),
        ),
    ]
