# Generated by Django 2.1.8 on 2020-04-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200419_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('BUSINESS STUDIES', 'Business Studies'), ('ENGLISH', 'English'), ('ICT', 'Ict')], default='Science', max_length=100),
        ),
    ]
