# Generated by Django 3.0.5 on 2020-05-02 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200501_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name_of_chapter', chained_model_field='course_name', default='', on_delete=django.db.models.deletion.CASCADE, to='course.Chapter'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 6, 56, 33, 610471, tzinfo=utc)),
        ),
    ]
