# Generated by Django 3.0.5 on 2020-05-10 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200510_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 12, 53, 59, 688782, tzinfo=utc)),
        ),
    ]
