# Generated by Django 3.0.5 on 2020-05-02 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20200502_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name_of_chapter',
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='course_name', chained_model_field='name_of_course', default='', on_delete=django.db.models.deletion.CASCADE, to='course.Chapter'),
        ),
        migrations.AddField(
            model_name='topic',
            name='course_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 9, 51, 24, 617818, tzinfo=utc)),
        ),
    ]
