# Generated by Django 3.0.5 on 2020-05-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20200513_2105'),
        ('course', '0002_auto_20200510_0938'),
    ]

    operations = [
    ]
