# Generated by Django 3.0.5 on 2020-05-02 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_auto_20200424_1911'),
        ('course', '0015_auto_20200502_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='name_of_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='teacher.TeachersInfo'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 18, 50, 53, 548032, tzinfo=utc)),
        ),
    ]
