# Generated by Django 3.0.5 on 2020-05-02 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20200502_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video_link',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 13, 14, 37, 731291, tzinfo=utc)),
        ),
    ]
