# Generated by Django 3.0.5 on 2020-05-02 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200502_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='file_link',
            field=models.CharField(default=' ', max_length=400),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 18, 2, 3, 140895, tzinfo=utc)),
        ),
    ]
