# Generated by Django 3.0.5 on 2020-05-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(default='', max_length=500)),
                ('gallery_short_details', models.CharField(default='', max_length=2000)),
                ('gallery_thumbnail', models.ImageField(upload_to='gallery_thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_pic')),
                ('gallery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.Gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='event_name',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
