# Generated by Django 3.0.5 on 2020-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200513_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
